import './globals.css'
import { Toaster } from "@/components/ui/toast/toaster"
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/context/theme-provider'

const font = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body className={font.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
