import "./globals.css";

import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toast/toaster";
import { NextAuthProvider } from "@/context/auth-provider";
import { ThemeProvider } from "@/context/theme-provider";

const font = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movie Ticket Booking App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body className={font.className}>
        <NextAuthProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            {children}
            <Toaster />
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
